server:
  port: 9000
  servlet:
    context-path:
spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/learning
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 50
      order_inserts: true
      order_updates: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true